"""initial schema

Revision ID: 59683379e9ce
Revises:
Create Date: 2026-09-22 16:07:18.340358

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import mssql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "59683379e9ce"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "medical_code_type",
        sa.Column("med_code_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=20), nullable=True),
        sa.PrimaryKeyConstraint("med_code_type_id"),
    )
    op.create_table(
        "note_type",
        sa.Column("note_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("note_type_id"),
    )
    op.create_table(
        "patient_status_type",
        sa.Column("patient_status_type_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("patient_status_type_id"),
    )
    op.create_table(
        "user",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("display_name", sa.String(length=200), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("ms_entra_id", sa.String(length=100), nullable=True),
        sa.PrimaryKeyConstraint("user_id"),
    )
    op.create_table(
        "vendor",
        sa.Column("vendor_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=50), nullable=True),
        sa.PrimaryKeyConstraint("vendor_id"),
    )
    op.create_table(
        "patient",
        sa.Column("patient_id", sa.Integer(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=True),
        sa.Column("last_name", sa.String(length=100), nullable=True),
        sa.Column("middle_name", sa.String(length=100), nullable=True),
        sa.Column("name_suffix", sa.String(length=20), nullable=True),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("nick_name", sa.String(length=100), nullable=True),
        sa.Column("date_of_birth", mssql.DATETIME2(), nullable=True),
        sa.Column("sex", sa.String(length=10), nullable=True),
        sa.Column("email", sa.String(length=200), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("social_security", sa.String(length=20), nullable=True),
        sa.Column("temp_race", sa.String(length=50), nullable=True),
        sa.Column("temp_marital_status", sa.String(length=50), nullable=True),
        sa.Column("preferred_language", sa.String(length=50), nullable=True),
        sa.Column("weight_lbs", sa.Integer(), nullable=True),
        sa.Column("height_in", sa.Integer(), nullable=True),
        sa.Column("sharepoint_id", sa.Integer(), nullable=True),
        sa.Column("temp_user", sa.String(length=100), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("patient_id"),
    )
    op.create_table(
        "device",
        sa.Column("device_id", sa.Integer(), nullable=False),
        sa.Column("hardware_uuid", sa.String(length=100), nullable=True),
        sa.Column("name", sa.String(length=200), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("vendor_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
        ),
        sa.ForeignKeyConstraint(
            ["vendor_id"],
            ["vendor.vendor_id"],
        ),
        sa.PrimaryKeyConstraint("device_id"),
    )
    op.create_table(
        "emergency_contact",
        sa.Column("emergency_contact_id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=True),
        sa.Column("phone_number", sa.String(length=20), nullable=True),
        sa.Column("relationship", sa.String(length=50), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
        ),
        sa.PrimaryKeyConstraint("emergency_contact_id"),
    )
    op.create_table(
        "medical_code",
        sa.Column("med_code_id", sa.Integer(), nullable=False),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("med_code_type_id", sa.Integer(), nullable=True),
        sa.Column("timestamp_applied", mssql.DATETIME2(), nullable=True),
        sa.ForeignKeyConstraint(
            ["med_code_type_id"],
            ["medical_code_type.med_code_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
        ),
        sa.PrimaryKeyConstraint("med_code_id"),
    )
    op.create_table(
        "medical_necessity",
        sa.Column("medical_necessity_id", sa.Integer(), nullable=False),
        sa.Column("evaluation_datetime", mssql.DATETIME2(), nullable=True),
        sa.Column("temp_dx_code", sa.String(length=20), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
        ),
        sa.PrimaryKeyConstraint("medical_necessity_id"),
    )
    op.create_table(
        "patient_address",
        sa.Column("patient_address_id", sa.Integer(), nullable=False),
        sa.Column("street_address", sa.String(length=200), nullable=True),
        sa.Column("city", sa.String(length=100), nullable=True),
        sa.Column("temp_state", sa.String(length=10), nullable=True),
        sa.Column("zipcode", sa.String(length=10), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
        ),
        sa.PrimaryKeyConstraint("patient_address_id"),
    )
    op.create_table(
        "patient_insurance",
        sa.Column("patient_insurance_id", sa.Integer(), nullable=False),
        sa.Column("medicare_beneficiary_id", sa.String(length=20), nullable=True),
        sa.Column("primary_payer_id", sa.String(length=50), nullable=True),
        sa.Column("primary_payer_name", sa.String(length=100), nullable=True),
        sa.Column("secondary_payer_id", sa.String(length=50), nullable=True),
        sa.Column("secondary_payer_name", sa.String(length=100), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
        ),
        sa.PrimaryKeyConstraint("patient_insurance_id"),
    )
    op.create_table(
        "patient_note",
        sa.Column("patient_note_id", sa.Integer(), nullable=False),
        sa.Column("note_content", sa.NVARCHAR(), nullable=True),
        sa.Column("note_datetime", mssql.DATETIME2(), nullable=True),
        sa.Column("temp_user", sa.String(length=100), nullable=True),
        sa.Column("temp_note_type", sa.String(length=100), nullable=True),
        sa.Column("call_time_seconds", sa.Float(), nullable=True),
        sa.Column("is_manual", mssql.BIT(), nullable=True),
        sa.Column("start_call_datetime", mssql.DATETIME2(), nullable=True),
        sa.Column("end_call_datetime", mssql.DATETIME2(), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("note_type_id", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["note_type_id"],
            ["note_type.note_type_id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.user_id"],
        ),
        sa.PrimaryKeyConstraint("patient_note_id"),
    )
    op.create_table(
        "patient_status",
        sa.Column("patient_status_id", sa.Integer(), nullable=False),
        sa.Column("temp_status_type", sa.String(length=50), nullable=True),
        sa.Column("modified_date", mssql.DATETIME2(), nullable=True),
        sa.Column("temp_user", sa.String(length=100), nullable=True),
        sa.Column("patient_id", sa.Integer(), nullable=True),
        sa.Column("patient_status_type_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["patient_id"],
            ["patient.patient_id"],
        ),
        sa.ForeignKeyConstraint(
            ["patient_status_type_id"],
            ["patient_status_type.patient_status_type_id"],
        ),
        sa.PrimaryKeyConstraint("patient_status_id"),
    )
    op.create_table(
        "blood_pressure_reading",
        sa.Column("blood_pressure_reading_id", sa.Integer(), nullable=False),
        sa.Column("temp_device", sa.String(length=100), nullable=True),
        sa.Column("recorded_datetime", mssql.DATETIME2(), nullable=True),
        sa.Column("received_datetime", mssql.DATETIME2(), nullable=True),
        sa.Column("systolic_reading", sa.Float(), nullable=True),
        sa.Column("diastolic_reading", sa.Float(), nullable=True),
        sa.Column("is_manual", mssql.BIT(), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.device_id"],
        ),
        sa.PrimaryKeyConstraint("blood_pressure_reading_id"),
    )
    op.create_table(
        "glucose_reading",
        sa.Column("glucose_reading_id", sa.Integer(), nullable=False),
        sa.Column("temp_device", sa.String(length=100), nullable=True),
        sa.Column("recorded_datetime", mssql.DATETIME2(), nullable=True),
        sa.Column("received_datetime", mssql.DATETIME2(), nullable=True),
        sa.Column("glucose_reading", sa.Float(), nullable=True),
        sa.Column("is_manual", mssql.BIT(), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.device_id"],
        ),
        sa.PrimaryKeyConstraint("glucose_reading_id"),
    )
    op.create_table(
        "medical_code_device",
        sa.Column("medical_code_device_id", sa.Integer(), nullable=False),
        sa.Column("med_code_id", sa.Integer(), nullable=True),
        sa.Column("device_id", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ["device_id"],
            ["device.device_id"],
        ),
        sa.ForeignKeyConstraint(
            ["med_code_id"],
            ["medical_code.med_code_id"],
        ),
        sa.PrimaryKeyConstraint("medical_code_device_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("medical_code_device")
    op.drop_table("glucose_reading")
    op.drop_table("blood_pressure_reading")
    op.drop_table("patient_status")
    op.drop_table("patient_note")
    op.drop_table("patient_insurance")
    op.drop_table("patient_address")
    op.drop_table("medical_necessity")
    op.drop_table("medical_code")
    op.drop_table("emergency_contact")
    op.drop_table("device")
    op.drop_table("patient")
    op.drop_table("vendor")
    op.drop_table("user")
    op.drop_table("patient_status_type")
    op.drop_table("note_type")
    op.drop_table("medical_code_type")
    # ### end Alembic commands ###
