"""Alembic's migrations are a second, independent description of the GPS schema next to
`models.py` itself -- the same kind of drift risk `test_generate_schema.py` guards
against for `sql/schema.sql`, but for `alembic/versions/*.py`. These tests run the real
migration chain against a real database and confirm it lands exactly on what the models
say the schema should be (see decision 0016).
"""

from pathlib import Path

import pytest
from alembic.config import Config

from alembic import command
from tests.integration.conftest import DB_HOST, DB_PASSWORD, DB_PORT, DB_USER, _connect

pytestmark = pytest.mark.integration

ALEMBIC_INI = Path(__file__).resolve().parents[2] / "alembic.ini"


@pytest.fixture
def alembic_config(monkeypatch, test_database):
    monkeypatch.setenv("GPS_SQL_USERNAME", DB_USER)
    monkeypatch.setenv("GPS_SQL_PASSWORD", DB_PASSWORD)
    monkeypatch.setenv("GPS_SQL_HOST", f"{DB_HOST},{DB_PORT}")
    monkeypatch.setenv("GPS_SQL_DB", test_database)
    return Config(str(ALEMBIC_INI))


def test_upgrade_head_has_no_drift_from_the_models(alembic_config):
    """`alembic upgrade head` against an empty database, then `alembic check`: no
    migration missing, none stale. `command.check()` raises
    `AutogenerateDiffsDetected` on any difference and returns quietly when there is
    none, so a clean return is the pass condition here."""
    command.upgrade(alembic_config, "head")
    command.check(alembic_config)


def test_downgrade_to_base_drops_every_table(alembic_config, test_database):
    command.upgrade(alembic_config, "head")
    command.downgrade(alembic_config, "base")

    db = _connect(test_database)
    try:
        # alembic_version is Alembic's own tracking table, left behind (empty) by
        # design -- it is what records that base has no migrations applied.
        rows = db.read_sql(
            "SELECT COUNT(*) AS n FROM INFORMATION_SCHEMA.TABLES "
            "WHERE TABLE_TYPE = 'BASE TABLE' AND TABLE_NAME != 'alembic_version'"
        )
    finally:
        db.close()
    assert rows["n"].iloc[0] == 0
